/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

WM_MESSAGE dMsg;

int i;
char acText[] = "1111111 22222222 33333333";
int cursor_set[2]={10,10};
GUI_RECT Rect = {10, 10, 59, 59};
GUI_WRAPMODE aWm[] = {GUI_WRAPMODE_NONE,
                      GUI_WRAPMODE_CHAR,
                      GUI_WRAPMODE_WORD};
/*
*********************************************************************************************************
*	函 数 名: MainTask
*	功能说明: GUI主函数
*	形    参：无
*	返 回 值: 无
*********************************************************************************************************
*/
static void cursor(/*WM_MESSAGE * pMsg*/)
{
	int                      Key;
	/*switch (pMsg->MsgId) 
	{
		case WM_KEY:
			if (((const WM_KEY_INFO *)(pMsg->Data.p))->PressedCnt > 0) 
			{*/
				Key = GUI_GetKey();
				switch(Key)
				{
					case GUI_KEY_LEFT:
						cursor_set[0]	 -=10;
						if(cursor_set[0] < 5)
							cursor_set[0]  = 5;
						break;
					case GUI_KEY_RIGHT:
						cursor_set[0]+=10;
						if(cursor_set[0] > 127)
							cursor_set[0]  = 127;
						break;
					case GUI_KEY_UP:
						cursor_set[1]-=10;
						if(cursor_set[1] < 5)
							cursor_set[1]  = 5;
						break;
					case GUI_KEY_DOWN:
						cursor_set[1]+=10;
						if(cursor_set[1] > 159)
							cursor_set[1]  = 159;
						break;
					case GUI_KEY_ENTER:
						cursor_set[1]    +=  60;
						if(cursor_set[1] > 159)
							cursor_set[1]  = 159;
						break;
					default:break;
				}
			/*}
			break;
		default:
			break;
	}*/
	
}
void MainTask(void) 
{
	
    GUI_Init();
		GUI_CURSOR_Show();
    GUI_SetTextMode(GUI_TM_TRANS);
	
    for (i = 0; i < 3; i++) 
    {
        GUI_SetColor(GUI_BLUE);
        GUI_FillRectEx(&Rect);
        GUI_SetColor(GUI_WHITE);
        GUI_DispStringInRectWrap(acText, &Rect, GUI_TA_LEFT, aWm[i]);
        Rect.y0 += 60;
        Rect.y1 += 60;
    }
	
    while (1)
    {
				cursor();
				GUI_CURSOR_SetPosition(cursor_set[0],cursor_set[1]);
        GUI_Delay(10);
    }
}
/*************************** End of file ****************************/
