Import('RTT_ROOT')
Import('rtconfig')
from building import *

#cwd     = GetCurrentDir()
cwd     = os.path.join(str(Dir('#')), 'Demo')
# The set of source files associated with this SConscript file.
#src = Split("""
#""")
src	= Glob('*.c')

CPPPATH = [cwd]
# The set of source files associated with this SConscript file.
path = [RTT_ROOT + '/components/emWin', RTT_ROOT + '/components/emWin/inc']

CPPDEFINES = []


group = DefineGroup('emWinDemo', src, depend = ['RT_USING_EMWIN_DEMO'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
